// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdKcfDWQPHDWiIIoGK636t-JMTIN5Uax8',
    appId: '1:791024450122:web:58f127f67d4b409680c4b3',
    messagingSenderId: '791024450122',
    projectId: 'my-newsapp-project',
    authDomain: 'my-newsapp-project.firebaseapp.com',
    storageBucket: 'my-newsapp-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC26F4sJIq6K8o3jXfCiVld4a6F392c5w',
    appId: '1:791024450122:android:2ef4b891816a056480c4b3',
    messagingSenderId: '791024450122',
    projectId: 'my-newsapp-project',
    storageBucket: 'my-newsapp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjfQ91dEdmgN1H9Nj-w2L_SFGZHMPgqOE',
    appId: '1:791024450122:ios:150799c9b8a7c0a780c4b3',
    messagingSenderId: '791024450122',
    projectId: 'my-newsapp-project',
    storageBucket: 'my-newsapp-project.appspot.com',
    iosBundleId: 'com.example.samples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjfQ91dEdmgN1H9Nj-w2L_SFGZHMPgqOE',
    appId: '1:791024450122:ios:150799c9b8a7c0a780c4b3',
    messagingSenderId: '791024450122',
    projectId: 'my-newsapp-project',
    storageBucket: 'my-newsapp-project.appspot.com',
    iosBundleId: 'com.example.samples',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdKcfDWQPHDWiIIoGK636t-JMTIN5Uax8',
    appId: '1:791024450122:web:0236f9d7ab5ea34880c4b3',
    messagingSenderId: '791024450122',
    projectId: 'my-newsapp-project',
    authDomain: 'my-newsapp-project.firebaseapp.com',
    storageBucket: 'my-newsapp-project.appspot.com',
  );
}
